### ISSUE TITLE
图库页面设置缺少顶部大图链接配置，移动端模式切换按钮无法使用

### ISSUE THREAD

**Issue by PuZhiweizuishuai** [chengzhongxue/halo-theme-hao#759]
### 是什么版本出现了此问题？

 2.16.3

### 发生了什么？

# 图库页面缺少顶部图片卡片背景图片配置选项

[photos.html](https://github.com/chengzhongxue/halo-theme-hao/blob/725860a0484dbf7468ad6a2e250be4cd390d25d5/templates/photos.html#L45C1-L46C91) 文件在前端模板中写了 `backgroundImg`，但是在配置文件 setting.yml 却缺少了这个选项

```html
                    <th:block th:if="${#strings.isEmpty(param.group)}"
                              th:with="background = ${theme.config.photos.backgroundImg}">
```

目前 setting.yml 图库部分配置如下

```yml
    - group: photos
      label: 图库
      formSchema:
        - $formkit: select
          name: photosStyle
          id: photosStyle
          key: photosStyle
          label: 样式
          value: default
          options:
            - value: default
              label: 默认
            - value: one
              label: 样式一
        - $formkit: text
          name: topLink
          key: topLink
          if: $get(photosStyle).value == 'default'
          label: 返回地址 (填写图库分组地址)
          value: "/album"
        - $formkit: text
          if: $get(photosStyle).value == 'default'
          name: detail
          label: 描述
          value: 每一张照片都是一次美好的记忆。
        - $formkit: radio
          name: tagEnable
          label: 图片标签
          value: false
          help: 图片左上角标签
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
```

建议增加此配置

```yml
        - $formkit: text
          if: $get(photosStyle).value == 'default'
          name: backgroundImg
          label: 背景图片
          value: 
```

# 移动端模式切换按钮无法使用

该文件 [sidebar.html](https://github.com/chengzhongxue/halo-theme-hao/blob/725860a0484dbf7468ad6a2e250be4cd390d25d5/templates/modules/sidebar.html#L7C1-L7C113) 调用的显示模式切换方法无法正常使用

```html
<a class="darkmode_switchbutton menu-child" href="javascript:void(0);" onclick="rm.switchDarkMode()"
```

![屏幕截图 2024-06-22 232603](https://github.com/chengzhongxue/halo-theme-hao/assets/32362404/d54fbc48-9520-4524-9862-4d607933fecc)

建议修改为和PC端一样的切换方法

```html
onclick="navFn.switchDarkMode();"
```

# 移动端侧边栏无法显示导航内容

这个我不知道是不是bug，还是有别的设置，移动端侧边栏 [sidebar.html](https://github.com/chengzhongxue/halo-theme-hao/blob/725860a0484dbf7468ad6a2e250be4cd390d25d5/templates/modules/sidebar.html#L13) 这部分内容无法显示相应的导航内容

```html
        <th:block th:if="${not #strings.isEmpty(theme.config.nav.leftMenu) && theme.config.nav.menus.phone_leftMenu}"
                  th:with="leftMenu = ${menuFinder.getByName(theme.config.nav.leftMenu)}">
            <div class="back-menu-list-groups">
                <div class="back-menu-list-group" th:each="menuItem : ${leftMenu.menuItems}">

                    <th:block th:if="${not #lists.isEmpty(menuItem.children)}">
                        <!-- 菜单必须有子项才会展示 -->
                        <div class="back-menu-list-title" th:text="${menuItem.status.displayName}"></div>
                        <div class="back-menu-list">
                            <th:block th:each="childMenu : ${menuItem.children}">
                                <a class="back-menu-item" rel="external nofollow"
                                   target="_blank" th:href="@{${childMenu.status.href}}">
                                    <!-- icon -->
                                    <img th:if="${!#strings.isEmpty(#annotations.getOrDefault(childMenu, 'icon', ''))}"
                                         class="back-menu-item-icon"
                                         th:src="${#annotations.getOrDefault(childMenu, 'icon', '')}">
                                    <span class="back-menu-item-text" th:text="${childMenu.status.displayName}"></span>
                                </a>
                            </th:block>
                        </div>

                    </th:block>
                </div>

            </div>
        </th:block>
```
![屏幕截图 2024-06-22 234001](https://github.com/chengzhongxue/halo-theme-hao/assets/32362404/fd1435b4-c1b4-4f32-b2ea-cbefe7ded20c)

因为没仔细研究过halo的主题编写文档，我目前的解决方案是直接复制PC端导航内容替换此部分内容

```html
        <th:block th:if="${not #strings.isEmpty(theme.config.nav.leftMenu) && theme.config.nav.menus.phone_leftMenu}"
                  th:with="leftMenu = ${menuFinder.getByName(theme.config.nav.leftMenu)}">
            <div class="back-menu-list-groups">
                <div class="back-menu-list-group" th:each="menuItem : ${leftMenu.menuItems}">

                    <th:block th:if="${not #lists.isEmpty(menuItem.children)}">
                        <!-- 菜单必须有子项才会展示 -->
                        <div class="back-menu-list-title" th:text="${menuItem.status.displayName}"></div>
                        <div class="back-menu-list">
                            <th:block th:each="childMenu : ${menuItem.children}">
                                <a class="back-menu-item" rel="external nofollow"
                                   target="_blank" th:href="@{${childMenu.status.href}}">
                                    <!-- icon -->
                                    <img th:if="${!#strings.isEmpty(#annotations.getOrDefault(childMenu, 'icon', ''))}"
                                         class="back-menu-item-icon"
                                         th:src="${#annotations.getOrDefault(childMenu, 'icon', '')}">
                                    <span class="back-menu-item-text" th:text="${childMenu.status.displayName}"></span>
                                </a>
                            </th:block>
                        </div>

                    </th:block>
                </div>

            </div>
        </th:block>
```

修改后的效果如下

![屏幕截图 2024-06-22 234356](https://github.com/chengzhongxue/halo-theme-hao/assets/32362404/ac445507-031f-4d00-8561-79dcd19b40cf)
